### PR TITLE
Pull request for youtube clone page - code review request

### PR DESCRIPTION
**Pull request by uryelah**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great effort :clap: :clap: . Almost done. However, you still have to implement the following changes. check below :arrow_down: 

- [REQUIRED] Add linter config to your repository and fix the possible errors. :no_entry_sign: 
- [OPTIONAL] I encourage you to use [semantic Html elements](https://www.w3schools.com/html/html5_semantic_elements.asp) and wrap your container divs inside them :nerd_face: 
- [REQUIRED] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload).

### That's it :relaxed: . When finished kindly resubmit another code review request :pray:

**Comment by santiago-dev96** [comment]
Just **finished everything that is REQUIRED**, but we **decided not to pay too much attention to the semantics for this project**, we'll keep that aspect in mind for future projects.

**Review by wathigo — APPROVED** [review]
### Hi Devs,
Great work so far. 
Just one thing though, 
Remember to give this Pull request a description of the completed tasks to make it look more professional. 
After that, **you can go ahead and merge**.
_Good luck in your future projects :)_

**Pull request merged**
